export const logs = {
  infoLogs: {
    INITIALIZE_CLIENT: "Initializing skyflow client",
    CLIENT_INITIALIZED:"Skyflow client initialized",
    CREATE_COLLECT_CONTAINER: "Creating Collect container",
    COLLECT_CONTAINER_CREATED:"Created Collect container",
    CREATE_REVEAL_CONTAINER: "Creating Reveal container",
    VALIDATE_RECORDS: "Validating records",
    VALIDATE_DETOKENIZE_INPUT: "Validating detokenize input",
    CREATING_ELEMENT:"Creating element",
    MOUNTING_ELEMENT:"Mounting element",
    ELEMENT_MOUNTED: "Element mounted",
    COLLECT_SUBMIT_SUCCESS: "Data has been collected successfully.",
    REVEAL_SUBMIT_SUCCESS:"Data has been revealed successfully.",
    INSERT_DATA_SUCCESS:"Data has been inserted successfully.",
    DETOKENIZE_SUCCESS:"Data has been revealed successfully.",
    GET_BY_ID_SUCCESS:"Data has been revealed successfully."

  },
  errorLogs: {
    INVALID_VAULT_ID:"Vault Id is invalid or cannot be found.",
    EMPTY_VAULT_ID:"VaultID is empty.",
    INVALID_BEARER_TOKEN:"Bearer token is invalid or expired.",
    INVALID_TABLE_NAME:"Table Name passed doesn’t exist in the vault with id ",
    INVALID_CREDENTIALS: "Invalid client credentials",
    INVALID_CONTAINER_TYPE: "Invalid container type",
    RECORDS_KEY_NOT_FOUND: "records object key value not found",
    EMPTY_RECORD: "records object is empty",
    EMPTY_TABLE_NAME:"Table Name is empty.",
    RECORDS_KEY_ERROR:"Key “records” is missing or payload is incorrectly formatted",
    TABLE_KEY_ERROR:"Key “table” is missing or payload is incorrectly formatted.",
    FIELDS_KEY_ERROR:"Key “fields” is missing or payload is incorrectly formatted",
    INVALID_COLUMN_NAME:"Column with given name is not present in the table in vault",
    EMPTY_COLUMN_NAME:"Column name is empty",
    // INVALID_DATA_TYPE:"",
    // VALIDATION_FAILED:"",
    INVALID_TOKEN_ID:"Token provided is invalid",
    EMPTY_TOKEN_ID:"Token is empty",
    ID_KEY_ERROR:"Key 'token' is missing in the payload provided",
    REDACTION_KEY_ERROR:"Key “redaction” is missing or payload is incorrectly formatted",
    INVALID_REDACTION_TYPE:"Redaction type value isn’t one of: “PLAIN_TEXT”, “REDACTED” ,“DEFAULT” or “MASKED”",

    EMPTY_TABLE_AND_FIELDS:
      "table or fields parameter cannot be passed as empty",
    EMPTY_TABLE: "Table can't be passed as empty",
    MISSING_RECORDS: "Missing records property",
    EMPTY_RECORDS: "Empty Records",
    EMPTY_RECORD_OBJECT: "Record cannot be Empty Object",
    MISSING_TOKEN: "Missing token property",
    MISSING_REDACTION: "Missing Redaction property",
    MISSING_IDS: "Missing ids property",
    INVALID_TABLE_OR_COLUMN:"Invalid table or column",
    EMPTY_RECORD_IDS: "Record ids cannot be Empty",
    INVALID_RECORD_ID_TYPE: "Invalid Type of Records Id",
    MISSING_TABLE: "Missing Table Property",
    INVALID_RECORD_TABLE_VALUE: "Invalid Record Table value",
    INVALID_RECORD_LABEL: "Invalid Record Label Type",
    INVALID_RECORD_ALT_TEXT: "Invalid Record altText Type",
    MISSING_GATEWAY_URL: "gateway URL Key is Missing",
    INVALID_GATEWAY_URL_TYPE: "Invalid gateway URL type",
    INVALID_GATEWAY_URL: "Invalid gateway URL",
    MISSING_METHODNAME_KEY: "methodName Key is Missing",
    INVALID_METHODNAME_VALUE: "Invalid methodName value",
    UNIQUE_ELEMENT_NAME: "The element name has to unique:",
    INVALID_IFRAME: "Expecting a valid Iframe",
    INVALID_FIELD: "Invalid Field",
    INVALID_ELEMENT_TYPE: "Provide valid element type",
    CANNOT_UPDATE_NAME: "Name attribute can't be updated",
    CANNOT_UPDATE_SENSITIVE: "Sensitive attribute can't be updated",
    MASK_REQUIRED: "mask option has to be array or undefined",
    MASK_ARRAY_STRING: "mask array values has to be string",
    REPLACE_PATTERN_ERROR: "replacePatterns array values has to be string",
    REQUIRE_RADIO_CHECKBOX_VALUE:
      "Elements radio and checkbox requires value attribute",
    ELEMENT_DROPDOWN_ERROR:
      "Element dropdown requires options attribute with an array of objects containing value and text attributes",
    CANNOT_CHANGE_ELEMENT: "Element can't be changed",
    ELEMENT_NOT_MOUNTED: "Element Not Mounted",
    FRAME_NOT_FOUND: "frame not found:",
    CLIENT_CONNECTION: "client connection not established",
    COMPLETE_AND_VALID_INPUTS: "Provide complete and valid inputs",
    REQUIRED_PARAMS_NOT_PROVIDED: "Required params are not provided",
    SENSITIVITY_INCOMPATIBLE: "Sensitivity is not backward compatible",
    INVALID_EVENT_TYPE: "Provide a valid event type",
    INVALID_EVENT_LISTENER: "Provide valid event listener",
    UNKNOWN_ERROR: "Unknown Error",
    INVALID_ELEMENT_SELECTOR:
      "Provided element selector is not valid or not found",
    TRANSACTION_ERROR: "An error occurred during transaction",
    CONNECTION_ERROR: "Error while initializing the connection",
    ERROR_OCCURED: "Error occurred",
    MISSING_TOKEN_KEY:"token key is Missing",
    MISSING_REDACTION_VALUE:"Missing redaction value",
    ELEMENT_MUST_HAVE_TOKEN:"Element must have token"
  },
};
