name: Public Beta Release

on:
 push:
    tags: '*.*.*-beta.*'
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - "*.md"

      
jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_ACTIONS }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          registry-url: 'https://registry.npmjs.org'
      
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - run: npm install
      
      - name: npm build
        run: npm run build-browser-sdk
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.SANDBOX_IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ steps.previoustag.outputs.tag }}/${{ secrets.SANDBOX_IFRAME_SECURE_SITE }}"

      - name: npm build iframe
        run: npm run build-iframe
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.SANDBOX_IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ steps.previoustag.outputs.tag }}/${{ secrets.SANDBOX_IFRAME_SECURE_SITE }}"

      - name: Configure AWS credentials Sandbox account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.SANDBOX_AWS_REGION }}

      - name: Set latest tag
        run: |
          mkdir tags
          echo "v${{ steps.previoustag.outputs.tag }}" > tags/latest

      - name: Deploy latest tag to S3
        run:
          aws s3 cp --recursive tags s3://${{secrets.SANDBOX_AWS_BUCKET_NAME}}/

      - name: Remove latest tag
        run: |
          rm -rf tags

      - name: Deploy to S3
        run:
          aws s3 cp --recursive dist/v1 s3://${{secrets.SANDBOX_AWS_BUCKET_NAME}}/v${{ steps.previoustag.outputs.tag }}/

      - name: build node-sdk
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.SANDBOX_IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ steps.previoustag.outputs.tag }}/${{ secrets.SANDBOX_IFRAME_SECURE_SITE }}"
        run: |
          npm run build:types 
          npm run build-node-sdk

      # - name: Get Previous tag
      #   id: previoustag
      #   uses: WyriHaximus/github-action-get-previous-tag@v1
      #   with:
      #     fallback: 1.0.0

      # - name: Bump Version
      #   run: |
      #      chmod +x ./scripts/bump_version.sh
      #      ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}"

      # - name: Commit changes
      #   run: |
      #      git config user.name ${{ github.actor }}
      #      git config user.email ${{ github.actor }}@users.noreply.github.com
      #      git add package.json
      #      git commit -m "[AUTOMATED] Beta Release - ${{ steps.previoustag.outputs.tag }}"
      #      git push origin
          
      - name: publish to npm
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

          
  aws-cf-invalidate:
    runs-on: ubuntu-latest
    needs: [build-sdk]
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0      
    - name: Configure AWS credentials SANDBOX account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ secrets.SANDBOX_AWS_REGION }}
    - name: invalidate-cf-distribution
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.SANDBOX_CF_DISTRIBUTION_ID }} --paths "/*"
