name: Public Beta Release

on:
 push:
    tags: '*.*.*-beta.*'
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - "*.md"

      
jobs:
  beta-release:
    uses: ./.github/workflows/common-release.yml
    with:
      REGISTRY_URL: "https://registry.npmjs.org"
      TAG: "beta"
    secrets:
      IFRAME_SECURE_ORIGIN: ${{ secrets.SANDBOX_IFRAME_SECURE_ORIGIN }}
      IFRAME_SECURE_SITE: ${{ secrets.SANDBOX_IFRAME_SECURE_SITE }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_SECRET }}
      AWS_REGION: ${{ secrets.SANDBOX_AWS_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.SANDBOX_AWS_BUCKET_NAME }}
      CF_DISTRIBUTION_ID: ${{ secrets.SANDBOX_CF_DISTRIBUTION_ID }}
      PAT_ACTIONS: ${{ secrets.PAT_ACTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
