name: Common Release Workflow

on:
  workflow_call:
    inputs:
      TAG:
        required: true
        type: string
      REGISTRY_URL:
        required: false
        type: string
    secrets:
        PAT_ACTIONS:
            required: true
        IFRAME_SECURE_ORIGIN:
            required: true
        IFRAME_SECURE_SITE:
            required: true
        AWS_SECRET_ACCESS_KEY:
            required: true
        AWS_ACCESS_KEY_ID:
            required: true
        AWS_REGION:
            required: true
        AWS_BUCKET_NAME:
            required: true
        CF_DISTRIBUTION_ID:
            required: true
        JFROG_USERNAME:
            required: false
        JFROG_PASSWORD:
            required: false
        NODE_AUTH_TOKEN:
            required: false

jobs:
  build-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_ACTIONS }}
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6
          registry-url: ${{ inputs.REGISTRY_URL }}

      - run: npm install

      - name: Get Previous Tag
        run: |
          echo "TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Set RELEASE_VERSION
        run: |
          if [ "${{ inputs.TAG }}" == "internal" ]; then
            echo "RELEASE_VERSION=${{ env.TAG }}-dev.$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${{ env.TAG }}" >> $GITHUB_ENV
          fi

      - name: Bump Version
        run: |
          chmod +x ./scripts/bump_version.sh
          ./scripts/bump_version.sh "${{ env.RELEASE_VERSION }}"

      - name: Resolve Branch for the Tagged Commit
        id: resolve-branch
        if: ${{ inputs.tag == 'beta' || inputs.tag == 'public' }} 
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref_name }})

          BRANCH_NAME=$(git branch -r --contains $TAG_COMMIT | grep -v 'HEAD ->' | grep -o 'origin/.*' | sed 's|origin/||' | head -n 1)

          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: Could not resolve branch for the tag."
            exit 1
          fi

          echo "Resolved Branch Name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Commit Changes
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git checkout ${{ env.branch_name }}
          git add package.json
          git commit -m "[AUTOMATED] Release - ${{ env.RELEASE_VERSION }}"
          git push origin ${{ env.branch_name }} -f

      - name: Build Browser SDK
        run: npm run build-browser-sdk
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{  env.RELEASE_VERSION }}/${{ secrets.IFRAME_SECURE_SITE }}"

      - name: Build Iframe
        run: npm run build-iframe
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{  env.RELEASE_VERSION }}/${{ secrets.IFRAME_SECURE_SITE }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Latest Tag
        run: |
          mkdir tags
          echo "v${{ env.RELEASE_VERSION }}" > tags/latest

      - name: Deploy Latest Tag to S3
        run: aws s3 cp --recursive tags s3://${{ secrets.AWS_BUCKET_NAME }}/

      - name: Remove Latest Tag
        run: rm -rf tags

      - name: Deploy to S3
        run: |
          aws s3 cp --recursive dist/v1 s3://${{ secrets.AWS_BUCKET_NAME }}/v${{ env.RELEASE_VERSION }}/

      - name: Build Node SDK
        run: |
          npm run build:types 
          npm run build-node-sdk
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{  env.RELEASE_VERSION }}/${{ secrets.IFRAME_SECURE_SITE }}"

      - name: Publish SDK
        run: |
          if [ "${{ inputs.TAG }}" == "beta" ]; then
            npm publish --tag ${{ inputs.TAG }}
          elif [ "${{ inputs.TAG }}" == "internal" ]; then
            curl -u ${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_PASSWORD }} https://prekarilabs.jfrog.io/prekarilabs/api/npm/auth/ > ~/.npmrc
            npm config set registry https://prekarilabs.jfrog.io/prekarilabs/api/npm/npm/
            npm config set unsafe-perm true
            npm publish
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Invalidate CloudFront cache 10 times
        run: |
          for i in {1..10}; do
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
              --paths "/*"
            sleep 10
          done
