name: CI


on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check JIRA ID
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(\[?[A-Z]{1,5}-[1-9][0-9]*)|(\[AUTOMATED\])|(Merge)|(Release).+$'
          flags: 'gm'
          excludeDescription: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.PAT_ACTIONS }}
          error: 'One of your your commit messages is not matching the format with JIRA ID Ex: ( SDK-123 commit message )'
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install modules
        run: npm ci

      - name: Check code quality
        uses: stefanoeb/eslint-action@1.0.2

      - name: Run tests
        run: npm run test
      
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_REPO_UPLOAD_TOKEN }}
          files: coverage/lcov.info
          name: codecov-skyflow-js
          verbose: true
      
      - name: Browser Build
        run: npm run build-browser-sdk
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ secrets.TEST_IFRAME_SECURE_SITE }}"

      - name: Build iFrame
        run: npm run build-iframe
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ secrets.TEST_IFRAME_SECURE_SITE }}"

      - name: Build Node SDK
        env:
          IFRAME_SECURE_ORIGIN: ${{ secrets.IFRAME_SECURE_ORIGIN }}
          IFRAME_SECURE_SITE: "v${{ secrets.TEST_IFRAME_SECURE_SITE }}"
        run: |
          npm run build:types 
          npm run build-node-sdk
