name: Semgrep

# Run workflow each time code is pushed to your repository.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

 Semgrep-run:
  uses: skyflowapi/.github-private/.github/workflows/Semgrep.yml@main
  secrets: inherit
  
